
spring: 
    profiles: 
        active: -dev

----
spring: 
    profiles: dev
    application: 
        name: micro-cloud-config-dev

---
spring: 
    profiles: test
    application: 
        name: micro-cloud-config-test